description: Restores and saves fastlane cache of the passed directory.
parameters:
  directory:
    type: string
steps:
  - restore_cache:
      name: Restore gems cache
      keys: bundle-v1-{{ checksum "<< parameters.directory >>/Gemfile.lock" }}
  - run:
      name: Configure Installation Directory
      command: bundle config set path 'vendor/bundle'
      working_directory: << parameters.directory >>
  - run:
      name: Bundle Install
      command: bundle check || bundle install
      working_directory: << parameters.directory >>
  - save_cache:
      name: Save gems cache
      key: bundle-v1-{{ checksum "<< parameters.directory >>/Gemfile.lock" }}
      paths:
        - << parameters.directory >>/vendor/bundle
