description: "Restore/Get/Save cache of pods libs"
steps:
  - restore_cache:
      name: Restore pods
      key: pods-v1-{{ checksum "ios/Podfile.lock" }}
  - run:
      name: Install pods
      command: bundle exec pod install --deployment
      working_directory: ios
  - save_cache:
      name: Save pods specs and pods cache
      key: pods-v1-{{ checksum "ios/Podfile.lock" }}
      paths:
        - ~/.pods
        - ios/Pods
