docker:
  - image: cimg/android:2024.01.1-node
resource_class: large
shell: /bin/bash -eo pipefail
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
  GRADLE_OPTS: '-Xmx3g -XX:+HeapDumpOnOutOfMemoryError"'
steps:
  - checkout
  - prepare_workspace
  - restore_environment_variables
  - fetch_supported_versions
  - install_node_modules
  - restore_cache:
      name: Restore gradle cache
      key: android-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
  - install_fastlane:
      directory: android
  - run:
      name: '[FL] Prepare Android Keystore'
      command: bundle exec fastlane android keystore
      working_directory: android
  - run:
      name: '[FL] Build'
      command: bundle exec fastlane android build version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE}
      working_directory: android
  - run:
      name: Move aab
      command: mv ~/project/build/app/outputs/bundle/release/app-release.aab app-release.aab
  - store_artifacts:
      path: app-release.aab
  - run:
      name: Move apk
      command: mv ~/project/build/app/outputs/apk/release/app-release.apk app-release.apk
  - store_artifacts:
      path: app-release.apk
  - persist_to_workspace:
      root: .
      paths:
        - app-release.aab
        - app-release.apk
  - save_cache:
      name: Save gradle cache
      key: android-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
      paths:
        - ~/.gradle
  - persist_environment_variables
