#!/bin/sh

#
# Install this using:
# ln -s ../../.github/hooks/pre-commit .git/hooks/pre-commit
#

# Regenerate circle-ci config-yml
CONFIG=$(git diff --cached --name-only .circleci/src)

echo "$CONFIG" | ./scripts/circleci-update-config
echo "$CONFIG" | xargs git add .circleci/config.yml
