# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.63.0"

default_platform :ios

platform :ios do
  before_all do
    setup_ci
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      timeout: 0,
      lock_when_sleeps: false,
      unlock: true
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: 'fastlane/app_store_connect_api_key.p8',
      in_house: false
    )
    pilot(
      ipa: 'ios/chatbegruenung.ipa',
      app_identifier: 'app.chatbegruenung',
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deliver iOS App to Apple AppStore"
  lane :production_upload do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: 'fastlane/app_store_connect_api_key.p8',
      in_house: false
    )

    version_name = options[:version_name]
    build_config_name = options[:build_config_name]
    ipa_path = options[:ipa_path]

    puts("delivering #{build_config_name} v#{version_name}")

    # https://docs.fastlane.tools/actions/deliver/
    deliver(
      ipa: 'ios/chatbegruenung.ipa',
      submit_for_review: true,
      automatic_release: true,
      release_notes: {
        'de-DE' => "Wir haben die App weiter für dich verbessert und einige Fehler entfernt.",
      },
      force: true,
      skip_screenshots: true,
      skip_metadata: true,
      # We do not have inapp purchase
      precheck_include_in_app_purchases: false,
      # https://firebase.google.com/docs/analytics/configure-data-collection?platform=ios
      # https://support.google.com/firebase/answer/6318039?hl=en
      submission_information: { add_id_info_uses_idfa: false }
    )
  end

  desc "Build app"
  lane :build do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: 'fastlane/app_store_connect_api_key.p8',
      in_house: false
    )
    match(
      type: "appstore",
      platform: "ios",
      app_identifier: ["app.chatbegruenung", "app.chatbegruenung.ShareExtension", "app.chatbegruenung.NotificationService", "app.chatbegruenung.watchkitapp"],
      readonly: true,
    )

    # Allow codesign to access keys without prompting
    keychain_path = "~/Library/Keychains/#{ENV['MATCH_KEYCHAIN_NAME']}-db"
    sh "security unlock-keychain -p \"#{ENV['MATCH_KEYCHAIN_PASSWORD']}\" #{keychain_path}"
    sh "security set-keychain-settings -lut 3600 #{keychain_path}"
    sh "security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k \"#{ENV['MATCH_KEYCHAIN_PASSWORD']}\" #{keychain_path} || true"

    gym(
      scheme: "RocketChat",
      workspace: "RocketChat.xcworkspace",
      xcargs: "-allowProvisioningUpdates",
      output_name: "chatbegruenung"
    )
  end

  desc "Build app for Simulator"
  lane :build_simulator do
    gym(
      scheme: "RocketChat",
      workspace: "RocketChat.xcworkspace",
      destination: "generic/platform=iOS Simulator",
      skip_package_ipa: true,
      output_name: "Rocket.Chat",
      output_directory: "./fastlane/output",
      build_path: "./fastlane/build",
      configuration: "Release",
      derived_data_path: "./fastlane/derived_data",
      xcargs: "-parallelizeTargets -jobs 4 ARCHS=arm64"
    )
  end

  after_all do |lane|
    delete_keychain(name: ENV["MATCH_KEYCHAIN_NAME"])
  end

  error do |lane, exception|
    delete_keychain(name: ENV["MATCH_KEYCHAIN_NAME"])
  end
end
